browser:
  browserName: chrome
  headlessBrowser: false
  webElementTimeOut: 25

environment:
  test1:
    active: true
    envName: test1
    appUrl: https://petstore.octoperf.com/actions/Catalog.action
    eTitle: Selenium


